### ISSUE TITLE
"Patch Assembly" code type

### ISSUE THREAD

**Issue by skoolzout1** [BullyWiiPlaza/JGeckoU#73] opened 2020-04-29 11:24 UTC
I sent you a message on GBAtemp but im guessing you rarely use it anymore lol. This was the next best place I figured I could find you. Anyways here's the contents of my message:

I've recently been working on a code for BoTW that requires that I NOP and modify a couple instructions in executable memory. If I manually change the instructions using the Disassembler tab in Jgecko one at a time, it works perfectly with no crashes or anything. However, when I try to use Patch Assembly (the C2 code type) to write new instructions, the game freezes no matter what but the Wii U does NOT crash. I can still send TCPgecko commands and browse memory.

I am pretty certain I haven't made any typos or anything.. I noticed there is also no documentation on the C2 code type, so maybe I'm using it wrong? I've made sure TCPgecko is up to date.. not that its changed in the last 2 years..

Here is my 'code' so far

C2000000 0D64E3D8
2C030001 00000000
C2000000 0D64E3F4
60000000 00000000
C2000000 0D64E408
60000000 00000000
C2000000 0D64E40C
60000000 00000000

It just changes one instruction and nops 3 others.

Is this code type unfinished or am I using it wrong? I appreciate your help. Thank you.

**Comment by BullyWiiPlaza** [comment] 2020-04-29 11:37
Hi @skoolzout1 
The problem is that the code handler cannot overwrite any assembly code currently since it then triggers a kernel memory access violation.

This can only be bypassed with special kernel write code which JGecko U uses for its pokes. Cosmocortney's code handler is outdated, I was working on making a new one for the [`Wii U Plugin System`](https://github.com/Maschell/WiiUPluginSystem) actually which is planned to overcome the shortcomings of the old code handler. I know it's super late but better than never I guess and nobody else put any work into any of this the last couple years besides CosmoCortney and me.

**Comment by skoolzout1** [comment] 2020-04-29 12:27
I certainly can't blame you for losing motivation to work on outdated things that very very few people will ever appreciate. I had moved on from the Wii U and never looked back until recently when some BoTW speedrunners approached me to make a code for them as a tool to help discover new glitches. 

Due to the nature of the code, it is required that some instructions be NOP'd as the game writes to important addresses far faster than the codehandler can. Thanks to Cemu and Cheat engine, I'm able to find the instructions in executable memory that I need to modify. (Even though Cemu's debugger is absolute garbage)
It's now just a matter of getting those modified instructions into executable memory on the Wii U nicely..

Anyways, I just wanted to confirm that I wasn't doing something stupid and that I wasn't missing something obvious when using the C2 codetype. 

Maybe I can find some documentation on this "special kernel write" and find a way to do it within a single C0 type code. I feel like we've talked about it in our messages on GBAtemp years ago.. I can't fully remember. 

If worse comes to worse.. I suppose I can give the speedrunners instructions on how to go through the disassembler one-by-one  and modify all of the instructions :p

**Comment by BullyWiiPlaza** [comment] 2020-04-29 12:44
Thanks for your understanding yet again, very few people also appreciate my work (or other people's in that regard). Most people are just like "Whers teh code databais? My cods dun't wurk, pl0x fix! JGecko wunt conekt! I get errors, pl0x halp. My JGecko is 10 years old, why no wurk?"

Anyway, I forgot to tell you that I already developed a solution to the problem and it's called "Assembly RAM Writes". In JGecko U you can define addresses and values which you want to patch/overwrite and you can send it just fine like a regular code and it will work. https://www.youtube.com/watch?v=ufDNs6E7cl8

**Comment by skoolzout1** [comment] 2020-04-30 10:24
Well... I've definitely stared at that checkbox while making codes but I assumed it was related to the Raw Machine Code checkbox and didn't pay it any attention since I rarely write pure assembly codes...

This will definitely help out a lot. Thank you for pointing me in the right direction.

I suppose you can close this issue if you wish, unless you want to tag it as an Enhancement/feature reminder for the C2 code type. But I think this "Assembly RAM Writes" will cover what the C2 code type would do if it was working anyway.

If you ever need to get ahold of me for some reason, you can email me at gmail (im sure you can guess the address) or just add me on discord at skoolzout1#6969

Best wishes on all of your future projects and of course, thank you for all of the work you've done already.

**Comment by BullyWiiPlaza** [comment] 2020-10-31 17:52
I'm closing this issue since for the [TCP Gecko Plugin](https://www.youtube.com/watch?v=7_UlPHriceY) I already implemented kernel writing support for the code types which means that this request is automatically fulfilled once the TCP Gecko Plugin is released. The development is pretty much finished but Maschell also has to release the new Wii U Plugin System for the TCP Gecko Plugin to become publicly available.

**Closed by BullyWiiPlaza** 2020-10-31 17:52 UTC
