### ISSUE TITLE
Errors when doing anything with codes

### ISSUE THREAD

**Issue by boss69xd** [BullyWiiPlaza/JGeckoU#52] opened 2018-02-13 06:12 UTC
i get the following errors when doing anything with codes. (this is with auto save on)
![screenshot_2](https://user-images.githubusercontent.com/30028455/36135708-d94fda66-105a-11e8-8f6d-305b7c9f3fef.png)
^^^to fix this i have to delete the "archive.zip" in the codes folder.
![screenshot_1](https://user-images.githubusercontent.com/30028455/36135705-d52b032a-105a-11e8-91b5-64e2a03171dc.png)
^^^to fix this i have to restart.

**Comment by BullyWiiPlaza** [comment] 2018-02-14 13:05
Did you do anything special to the archive.zip to get this error? It should always work smoothly but apparently not. Does it even work sometimes or never?

**Comment by boss69xd** [comment] 2018-02-15 01:31
i did nothing special, it does sometime work but not always.

**Comment by BullyWiiPlaza** [comment] 2018-02-26 18:32
It should be fixed now. Put it to the test and let me know if it ever happened again. Thanks. :)

**Comment by boss69xd** [comment] 2018-02-26 22:42
Ok so the error of the archive.zip being corrupted still pops up and i still have to delete the .zip to fix it, but you did fix the bug of the code list getting shorter when you click on a small code, you also fixed the error that forced you to restart. It also takes a bit to enable and disable codes with auto save on.

**Comment by BullyWiiPlaza** [comment] 2018-02-28 06:00
I tried to make a fix for it again. Since it's always working fine for me, I can't really make sure that it's definitely fine. Let me know if it still happens then.

**Comment by boss69xd** [comment] 2018-03-04 22:58
So with the recent release of item targeting and I've tried to use darkflares stalking code BUT on both times using the codes i've always gotten this error using raw machine codes (yes i have 'RAW machine code' checked)
![screenshot_1](https://user-images.githubusercontent.com/30028455/36951788-73740bc4-1fd5-11e8-8dbf-a6d0af1ba9b4.png)

**Comment by BullyWiiPlaza** [comment] 2018-03-04 23:11
When you do what exactly? Save code or send codes?

**Comment by boss69xd** [comment] 2018-03-04 23:39
Send codes

**Comment by BullyWiiPlaza** [comment] 2018-03-05 10:43
It works for me:
![image](https://user-images.githubusercontent.com/7620135/36970865-48f5dd56-206a-11e8-91fb-c5699358ff67.png)
Did you make sure you downloaded the latest JGecko U and TCP Gecko Installer? I think this was an issue I fixed before.

**Comment by boss69xd** [comment] 2018-03-05 21:23
atm my laptop is being fixed but ill download JGecko U and TCPGecko once it is and test it....and yes the archive.zip error is fixed

**Comment by boss69xd** [comment] 2018-03-09 08:47
this is happening
![screenshot_1](https://user-images.githubusercontent.com/30028455/37198395-2faa861e-234c-11e8-8f07-31bf4a04a8a7.png)
also the same error occurs when sending raw machine code
it also threw a lot of errors at me when i first tried to send codes a few times

**Comment by BullyWiiPlaza** [comment] 2018-03-11 15:14
It works fine:
![image](https://user-images.githubusercontent.com/7620135/37255065-30032d3a-2547-11e8-95a3-2f2dfbaf8bed.png)
Make sure to download the latest version of JGecko U. I don't think it's broken. I'm closing this issue then.

**Closed by BullyWiiPlaza** 2018-03-11 15:14 UTC

**Comment by IlerWyatt** [comment] 2021-01-31 18:06
java.lang.IllegalStateException: java.net.SocketException: Connection reset
	at qmb.<init>(eah:254)
	at qmb.m(eah:282)
	at mO.p(geb:8183)
	at mO.G(geb:189)
	at PK.m(geb:5271)
	at PK.doInBackground(geb:6958)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at OLb.m(evg:111)
	at Tmb.L(tug:957)
	at Tmb.m(tug:1051)
	at qmb.m(eah:26)
	at qmb.<init>(eah:120)
	... 11 more



It's always the same thing when I try to connect it. and no, it's not to do with my TCPgecko Installation.

also when I try connecting it, it crashes the wii u.
